Repository codestates-seb/seb42_main_005, pull requests merged in 2023-03, with the labels that each got.

#24 BE_feat/user 컨트롤러 및 DTO 구현 완료
  back/src/main/java/com/project/mainproject/user/controller/UserController.java
  back/src/main/java/com/project/mainproject/user/dto/PostUserPatchDto.java
  back/src/main/java/com/project/mainproject/user/dto/PostUserSignUpDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserFindPasswordDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserInfoDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserPickedStoreDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserReviewDto.java
  back/src/main/java/com/project/mainproject/user/dto/UsersDto.java
  back/src/main/java/com/project/mainproject/user/dummy/UserData.java
Labels: enhancement

#26 Fe feat/pharmlists
  front/public/Images/Heart.png
  front/public/Images/OurPharmGo.png
  front/public/Images/UnHeart.png
  front/src/Components/Modal/PharmRank.tsx
  front/src/Components/Modal/TagContainer.tsx
  front/src/Components/PharmList/PharmList.tsx
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Components/Ul/PharmRank.tsx
Labels: enhancement

#27 BE_feat/Controller 및 DTO 구현
  back/src/main/java/com/project/mainproject/dto/PageInfo.java
  back/src/main/java/com/project/mainproject/dto/PageResponseDto.java
  back/src/main/java/com/project/mainproject/dto/SingleResponseDto.java
  back/src/main/java/com/project/mainproject/enums/ResultStatus.java
  back/src/main/java/com/project/mainproject/review/controller/AdminReviewController.java
  back/src/main/java/com/project/mainproject/review/controller/ReviewController.java
  back/src/main/java/com/project/mainproject/review/dto/GetReportedReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/GetReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/PostCreateReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/SimpleReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/StoreReviewPageDto.java
  back/src/main/java/com/project/mainproject/review/entity/Review.java
  back/src/main/java/com/project/mainproject/store/controller/StoreController.java
  back/src/main/java/com/project/mainproject/store/dto/GetPickedStoreDto.java
  back/src/main/java/com/project/mainproject/store/dto/GetStoreHomeDto.java
  back/src/main/java/com/project/mainproject/store/entity/Store.java
  back/src/main/java/com/project/mainproject/store/entity/StoreImage.java
  back/src/main/java/com/project/mainproject/tag/dto/TagIdDto.java
  back/src/main/java/com/project/mainproject/user/controller/AdminController.java
  back/src/main/java/com/project/mainproject/user/controller/UserController.java
  back/src/main/java/com/project/mainproject/user/dto/AdminUsersDto.java
  back/src/main/java/com/project/mainproject/user/dto/BannedReviewsDto.java
  back/src/main/java/com/project/mainproject/user/dto/PostUserPatchDto.java
  back/src/main/java/com/project/mainproject/user/dto/PostUserSignUpDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserFindPasswordDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserInfoDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserPickedStoreDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserReviewDto.java
  back/src/main/java/com/project/mainproject/user/dto/UsersDto.java
  back/src/main/java/com/project/mainproject/user/dummy/UserData.java
  back/src/main/java/com/project/mainproject/utils/UriCreator.java
Labels: enhancement

#47 Fe feat/header 헤더 구현 및 페이지 적용
  front/public/Images/Admin.png
  front/public/Images/Heart.png
  front/public/Images/Logo.png
  front/public/Images/Pharm.png
  front/public/Images/UnHeart.png
  front/public/Images/User.png
  front/src/App.tsx
  front/src/Components/Header/Account.tsx
  front/src/Components/Header/Header.tsx
Labels: enhancement

#53 FE_feat/pharmDetail 약국상세 모달 화면구현
  front/public/Images/emstar.png
  front/public/Images/fillstar.png
  front/public/Images/pharm.png
  front/public/Images/random.png
  front/public/Images/user.png
  front/public/Images/떡잎유치원.png
  front/public/Images/쌍화탕.jpg
  front/src/Components/Modal/PharmDetail.tsx
  front/src/Components/Modal/PharmInfo.tsx
  front/src/Components/Modal/Review.tsx
  front/src/Components/Modal/ReviewUnit.tsx
  front/src/Components/Modal/WriteReviewForm.tsx
  front/src/Components/PharmList/PharmDetail.tsx
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Components/Ul/Textarea.tsx
  front/src/Pages/Home.tsx
Labels: duplicate, enhancement, fix

#49 Fe feat/signup 화면 구현
  front/public/Images/LockPersonOutline.png
  front/public/Images/SignUpPill.png
  front/public/Images/cake.png
  front/public/Images/camera.png
  front/public/Images/person-outline.png
  front/public/Images/person-pencil .png
  front/public/Images/whereyoulive.png
  front/src/App.tsx
  front/src/Components/SignUpForm/PharmSignForms.tsx
  front/src/Components/SignUpForm/PharmSignUpForm.tsx
  front/src/Components/SignUpForm/SignUpFormTab.tsx
  front/src/Components/SignUpForm/UserSignUpForm.tsx
  front/src/Components/SignUpForm/UserSignUpForms.tsx
  front/src/Pages/SignUp.tsx
Labels: enhancement

#56 FE_style/pharmlist 약국리스트 레이아웃 및 CSS 수정
  front/src/App.tsx
  front/src/Components/Modal/PharmDetail.tsx
  front/src/Components/PharmList/PharmItem.tsx
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Components/Ul/PharmRank.tsx
Labels: fix

#57 FE_feat/adminReports 관리자 계정 <신고리뷰관리/> 화면구현
  front/src/Pages/Admin/AdminTabs.tsx
  front/src/Pages/Admin/Reports.tsx
Labels: enhancement

#59 Be_docs/User 기능문서화
  back/src/docs/asciidoc/index.adoc
  back/src/main/java/com/project/mainproject/review/dto/GetReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/PostReviewHateDto.java
  back/src/main/java/com/project/mainproject/store/dto/GetPickedStoreDto.java
  back/src/main/java/com/project/mainproject/user/controller/UserController.java
  back/src/main/java/com/project/mainproject/user/dto/UserFindPasswordDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserPatchDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserSignUpDto.java
  back/src/main/java/com/project/mainproject/user/dummy/UserStub.java
  back/src/test/java/com/project/mainproject/helper/ControllerTestHelper.java
  back/src/test/java/com/project/mainproject/helper/user/UserControllerTestHelper.java
  back/src/test/java/com/project/mainproject/review/controller/ReviewControllerTest.java
  back/src/test/java/com/project/mainproject/store/controller/StoreControllerTest.java
  back/src/test/java/com/project/mainproject/user/controller/UserControllerTest.java
Labels: documentation

#62 FE_feat/pharmDetail 관리자계정 전체회원관리 화면구현
  front/src/Pages/Admin/AdminTabs.tsx
  front/src/Pages/Admin/Reports.tsx
  front/src/Pages/Admin/Users.tsx
Labels: enhancement, fix

#61 Be_docs/rest docs user
  back/src/docs/asciidoc/index.adoc
  back/src/main/java/com/project/mainproject/review/controller/ReviewController.java
  back/src/main/java/com/project/mainproject/user/dto/UserInfoDto.java
  back/src/main/java/com/project/mainproject/user/dto/UsersDto.java
  back/src/main/java/com/project/mainproject/user/dummy/UserStub.java
  back/src/main/java/com/project/mainproject/user/entity/Normal.java
  back/src/main/java/com/project/mainproject/user/entity/Pharmacy.java
  back/src/main/java/com/project/mainproject/user/entity/User.java
  back/src/main/java/com/project/mainproject/user/enums/UserStatus.java
  back/src/test/java/com/project/mainproject/helper/user/UserControllerTestHelper.java
  back/src/test/java/com/project/mainproject/review/controller/ReviewControllerTest.java
  back/src/test/java/com/project/mainproject/user/controller/UserControllerTest.java
Labels: documentation

#63 FE_feat/mapAPI 지도 구현
  front/index.html
  front/package-lock.json
  front/package.json
  front/src/Components/Header/Layout.tsx
  front/src/Components/Map/Item1.tsx
  front/src/Components/Map/KakaoMap.tsx
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Pages/Home.tsx
Labels: enhancement

#64 FE_feat/adminCerfity 관리자계정 약사인증관리 화면구현
  front/src/Pages/Admin/AdminTabs.tsx
  front/src/Pages/Admin/Certify.tsx
  front/src/Pages/Admin/ImageUp.tsx
  front/src/Pages/Admin/Reports.tsx
  front/src/Pages/Admin/Users.tsx
Labels: enhancement

#73 Be_docs/rest docs 1차 완성
  back/build.gradle
  back/src/docs/asciidoc/index.adoc
  back/src/main/java/com/project/mainproject/dto/PageInfo.java
  back/src/main/java/com/project/mainproject/dto/PageResponseDto.java
  back/src/main/java/com/project/mainproject/dto/SingleResponseDto.java
  back/src/main/java/com/project/mainproject/dto/UserIdxRequestDto.java
  back/src/main/java/com/project/mainproject/dummy/CommonStub.java
  back/src/main/java/com/project/mainproject/review/controller/AdminReviewController.java
  back/src/main/java/com/project/mainproject/review/controller/ReviewController.java
  back/src/main/java/com/project/mainproject/review/dto/GetReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/ListGetReportedReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/ListGetStoreReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/PostReportReviewPlusDto.java
  back/src/main/java/com/project/mainproject/review/dto/PostReviewHateDto.java
  back/src/main/java/com/project/mainproject/review/dto/PostReviewLikeDto.java
  back/src/main/java/com/project/mainproject/review/dto/PostUpdateReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/ReportReviewResponseDto.java
  back/src/main/java/com/project/mainproject/review/dto/SimpleReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/StoreReviewPageDto.java
  back/src/main/java/com/project/mainproject/review/dummy/ReviewStub.java
  back/src/main/java/com/project/mainproject/store/controller/StoreController.java
  back/src/main/java/com/project/mainproject/store/dto/FilterTagDto.java
  back/src/main/java/com/project/mainproject/store/dto/GetPickedStoreDto.java
  back/src/main/java/com/project/mainproject/store/dto/GetStoreHomeListDto.java
  back/src/main/java/com/project/mainproject/store/dto/StoreIdxResponse.java
  back/src/main/java/com/project/mainproject/store/dummy/StoreStub.java
  back/src/main/java/com/project/mainproject/tag/dto/TagIdDto.java
  back/src/main/java/com/project/mainproject/user/controller/AdminController.java
  back/src/main/java/com/project/mainproject/user/controller/UserController.java
  back/src/main/java/com/project/mainproject/user/dto/AdminUsersDto.java
  back/src/main/java/com/project/mainproject/user/dto/BannedReviewsDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserFindPasswordDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserInfoDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserPatchDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserSignUpDto.java
  back/src/main/java/com/project/mainproject/user/dto/UsersDto.java
  back/src/main/java/com/project/mainproject/user/dummy/AdminStub.java
  back/src/main/java/com/project/mainproject/user/dummy/UserStub.java
  back/src/main/java/com/project/mainproject/user/entity/Normal.java
  back/src/main/java/com/project/mainproject/user/entity/Pharmacy.java
  back/src/main/java/com/project/mainproject/user/entity/User.java
  back/src/main/java/com/project/mainproject/user/enums/UserStatus.java
  back/src/main/java/com/project/mainproject/utils/UriCreator.java
  back/src/main/resources/static/docs/index.html
  back/src/test/java/com/project/mainproject/helper/ControllerTestHelper.java
  back/src/test/java/com/project/mainproject/helper/review/ReviewAdminControllerTestHelper.java
  back/src/test/java/com/project/mainproject/helper/review/ReviewControllerTestHelper.java
  back/src/test/java/com/project/mainproject/helper/store/StoreControllerTestHelper.java
  back/src/test/java/com/project/mainproject/helper/user/AdminControllerTestHelper.java
  back/src/test/java/com/project/mainproject/helper/user/UserControllerTestHelper.java
  back/src/test/java/com/project/mainproject/review/controller/ReviewAdminControllerTest.java
  back/src/test/java/com/project/mainproject/review/controller/ReviewControllerTest.java
  back/src/test/java/com/project/mainproject/store/controller/StoreControllerTest.java
  back/src/test/java/com/project/mainproject/user/controller/AdminControllerTest.java
  back/src/test/java/com/project/mainproject/user/controller/UserControllerTest.java
  back/src/test/java/com/project/mainproject/utils/ApiDocumentUtils.java
Labels: documentation

#72 FE_feat/signOut 탈퇴페이지 화면구현 완료
  front/src/Pages/Admin/ImageUp.tsx
  front/src/Pages/SignOut.tsx
Labels: enhancement

#75 FE_feat/filterCtrl 필터 컨트롤러 인터페이스 구현
  front/index.html
  front/src/App.tsx
  front/src/Components/Map/Item2.tsx
  front/src/Components/Map/Item3.tsx
  front/src/Components/Map/KakaoMap.tsx
  front/src/Components/Map/MapFilter.tsx
  front/src/Util/UseGeolocation.tsx
Labels: enhancement

#77 Fe feat/signup유효성검사
  front/package-lock.json
  front/package.json
  front/public/Images/LockPersonOutline.png
  front/public/Images/camera.png
  front/public/Images/google.png
  front/public/Images/person-outline.png
  front/public/Images/person-pencil .png
  front/public/Images/whereyoulive.png
  front/src/Components/SignUpForm/PharmSignForms.tsx
  front/src/Components/SignUpForm/SignUpFormTab.tsx
  front/src/Components/SignUpForm/SignUpInput.tsx
  front/src/Components/SignUpForm/UserSignUpForms.tsx
  front/src/Components/SignUpForm/Validation.tsx
  front/src/Pages/SignUp.tsx
Labels: enhancement

#79 Fe_feat/signup유효성검사_css수정
  front/src/Components/SignUpForm/ErrorAlert.tsx
  front/src/Components/SignUpForm/PharmSignForms.tsx
  front/src/Components/SignUpForm/SignUpInput.tsx
  front/src/Components/SignUpForm/UserSignUpForms.tsx
Labels: fix

#81 BE_feat/Error처리 1차 완성
  back/src/main/java/com/project/mainproject/exception/BusinessLogicException.java
  back/src/main/java/com/project/mainproject/exception/CommonExceptionCode.java
  back/src/main/java/com/project/mainproject/exception/ErrorResponse.java
  back/src/main/java/com/project/mainproject/exception/ExceptionCode.java
  back/src/main/java/com/project/mainproject/exception/advice/GlobalExceptionAdvice.java
  back/src/main/java/com/project/mainproject/review/exception/ReviewExceptionCode.java
  back/src/main/java/com/project/mainproject/store/exception/StoreExceptionCode.java
  back/src/main/java/com/project/mainproject/user/exception/UserExceptionCode.java
Labels: enhancement

#85 Fe_feat/login_화면구현
  front/src/Components/SignUpForm/UserSignUpForms.tsx
  front/src/Pages/Login.tsx
  front/src/Pages/SignUp.tsx
Labels: enhancement

#89 FE_feat/myInfo 일반계정 마이페이지 화면구현
  front/src/Components/SignUpForm/Validation.tsx
  front/src/Pages/Admin/AdminTabs.tsx
  front/src/Pages/Admin/Certify.tsx
  front/src/Pages/Pharm/MyPharmacy.tsx
  front/src/Pages/User/MyInfo.tsx
  front/src/Pages/User/MyInfo_Information.tsx
  front/src/Pages/User/MyInfo_likes.tsx
  front/src/Pages/User/MyInfo_reviews.tsx
Labels: enhancement

#91 Be feat/servce review create review
  back/src/main/java/com/project/mainproject/review/controller/ReviewController.java
  back/src/main/java/com/project/mainproject/review/dto/PostCreateReviewDto.java
  back/src/main/java/com/project/mainproject/review/entity/Review.java
  back/src/main/java/com/project/mainproject/review/mapper/ReviewMapper.java
  back/src/main/java/com/project/mainproject/review/service/ReviewService.java
  back/src/main/java/com/project/mainproject/store/entity/Store.java
  back/src/main/java/com/project/mainproject/store/entity/StoreImage.java
  back/src/main/java/com/project/mainproject/tag/entity/ReviewTag.java
  back/src/main/java/com/project/mainproject/tag/entity/Tag.java
  back/src/main/java/com/project/mainproject/tag/repository/ReviewTagRepository.java
  back/src/main/java/com/project/mainproject/tag/repository/TagRepository.java
  back/src/main/java/com/project/mainproject/user/entity/User.java
  back/src/main/resources/application.yml
Labels: enhancement

#90 FE_feat/FuncMap 지도 우리집/현위치 기능 구현
  front/index.html
  front/package-lock.json
  front/package.json
  front/public/Images/NoPharmImg.png
  front/public/Images/cake.png
  front/public/Images/currentPos.png
  front/public/Images/myPlace.png
  front/src/Components/Map/CurrentLocation.tsx
  front/src/Components/Map/KakaoMap.tsx
  front/src/Components/Map/MapFilter.tsx
  front/src/Components/Map/MapLogic.tsx
  front/src/Util/UseGeolocation.tsx
  front/src/Util/type.ts
  front/src/Util/z-index.ts
Labels: enhancement, fix

#96 Fe feat/ 코드수정
  front/src/Components/SignUpForm/ErrorAlert.tsx
  front/src/Components/SignUpForm/PharmSignForms.tsx
  front/src/Components/SignUpForm/SignUpFormTab.tsx
  front/src/Components/SignUpForm/SignUpInput.tsx
  front/src/Components/SignUpForm/UserSignUpForms.tsx
  front/src/Components/SignUpForm/Validation.tsx
  front/src/Components/Ul/Button.tsx
  front/src/Pages/Pharm/Pharmacist_Information.tsx
  front/src/Pages/Pharm/Pharmacy_Information.tsx
  front/src/Pages/SignUp.tsx
  front/src/Pages/User/InputAlert.tsx
  front/src/Pages/User/MyInfo_Information.tsx
  front/src/Pages/User/MyInfo_likes.tsx
  front/src/Pages/User/MyInfo_reviews.tsx
  front/src/Util/type.ts
Labels: fix

#99 FE_fix/pharmDetail
  front/src/Components/Modal/AnyDropDown.tsx
  front/src/Components/Modal/PharmDetail.tsx
  front/src/Components/Modal/WriteReviewForm.tsx
  front/src/Components/SignUpForm/PharmSignForms.tsx
  front/src/Components/SignUpForm/UserSignUpForms.tsx
Labels: fix

#104 FE_feat/FuncMap 지도 기능 추가
  front/package-lock.json
  front/package.json
  front/public/Images/Admin.png
  front/public/Images/OurPharmGo.png
  front/public/Images/Pharm.png
  front/public/Images/SignUpPill.png
  front/public/Images/User.png
  front/public/Images/pharm.png
  front/public/Images/user.png
  front/src/Components/Header/Account.tsx
  front/src/Components/Header/Header.tsx
  front/src/Components/Header/Layout.tsx
  front/src/Components/Map/KakaoMap.tsx
  front/src/Components/Map/MapFilter.tsx
  front/src/Components/Map/MapLogic.tsx
  front/src/Components/Modal/AnyDropDown.tsx
  front/src/Components/Modal/PharmDetail.tsx
  front/src/Components/Modal/PharmInfo.tsx
  front/src/Components/Modal/ReviewUnit.tsx
  front/src/Components/PharmList/PharmItem.tsx
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Components/SignUpForm/PharmSignForms.tsx
  front/src/Components/SignUpForm/SignUpFormTab.tsx
  front/src/Components/SignUpForm/UserSignUpForms.tsx
  front/src/Components/Ul/PharmRank.tsx
  front/src/Pages/Home.tsx
  front/src/Pages/SignUp.tsx
  front/src/Util/type.ts
  front/src/Util/z-index.ts
Labels: fix

#112 로그인유효성,비밀번호찾기유효성,시맨틱태그,css통일
  front/src/Pages/FindPW.tsx
  front/src/Pages/Login.tsx
Labels: enhancement

#115 Be feat/getStoreDetail기능구현 완료
  back/build.gradle
  back/src/main/java/com/project/mainproject/VO/OperatingTime.java
  back/src/main/java/com/project/mainproject/openApi/controller/OpenApiController.java
  back/src/main/java/com/project/mainproject/openApi/dto/HolidayDataDto.java
  back/src/main/java/com/project/mainproject/openApi/entity/HolidayData.java
  back/src/main/java/com/project/mainproject/openApi/service/OpenApiService.java
  back/src/main/java/com/project/mainproject/openApi/utils/JsonConverter.java
  back/src/main/java/com/project/mainproject/redis/config/RedisConfiguration.java
  back/src/main/java/com/project/mainproject/redis/repository/RedisRepository.java
  back/src/main/java/com/project/mainproject/redis/service/RedisService.java
  back/src/main/java/com/project/mainproject/store/controller/StoreController.java
  back/src/main/java/com/project/mainproject/store/dto/DBdto/DBStoreDetailDto.java
  back/src/main/java/com/project/mainproject/store/dto/GetStoreDetailDto.java
  back/src/main/java/com/project/mainproject/store/dto/OperatingDayOfWeekDto.java
  back/src/main/java/com/project/mainproject/store/dto/TodayOperatingTimeDto.java
  back/src/main/java/com/project/mainproject/store/entity/Store.java
  back/src/main/java/com/project/mainproject/store/mapper/StoreMapper.java
  back/src/main/java/com/project/mainproject/store/repository/StoreRepository.java
  back/src/main/java/com/project/mainproject/store/service/StoreGetService.java
  back/src/main/java/com/project/mainproject/store/service/StoreService.java
  back/src/main/java/com/project/mainproject/store/service/StoreValidService.java
  back/src/main/java/com/project/mainproject/store/utils/TransOperatingTime.java
  back/src/main/java/com/project/mainproject/user/entity/PickedStore.java
  back/src/main/java/com/project/mainproject/utils/UrlCreator.java
Labels: enhancement

#122 Fe feat/pharm detail axios
  front/package-lock.json
  front/package.json
  front/public/Data/Pharm.json
  front/public/Data/Review.json
  front/src/Components/Modal/AnyDropDown.tsx
  front/src/Components/Modal/PharmDetail.tsx
  front/src/Components/Modal/PharmInfo.tsx
  front/src/Components/Modal/ReviewOfReview.tsx
  front/src/Components/Modal/ReviewUnit.tsx
  front/src/Components/Modal/WriteReviewForm.tsx
  front/src/Components/PharmList/PharmItem.tsx
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Components/Ul/Input.tsx
  front/src/Components/Ul/Textarea.tsx
  front/src/Redux/slice/getPharmListSlice.ts
  front/src/Redux/slice/getPharmSlice.ts
  front/src/Redux/store/store.ts
Labels: enhancement

#121 Be_feat/data 공공 약국 데이터 조회 API 호출 및 DB 저장
  back/src/main/java/com/project/mainproject/VO/OperatingTime.java
  back/src/main/java/com/project/mainproject/data/controller/DataController.java
  back/src/main/java/com/project/mainproject/data/dto/RequestDetailDto.java
  back/src/main/java/com/project/mainproject/data/dto/RequestInfoDto.java
  back/src/main/java/com/project/mainproject/data/dto/RequestLocationDto.java
  back/src/main/java/com/project/mainproject/data/dto/RequestPageDto.java
  back/src/main/java/com/project/mainproject/data/dto/StoreDataDto.java
  back/src/main/java/com/project/mainproject/data/enums/DayOfTheWeek.java
  back/src/main/java/com/project/mainproject/data/mapper/DataMapper.java
  back/src/main/java/com/project/mainproject/data/service/DataService.java
  back/src/main/java/com/project/mainproject/data/utils/JsonConverter.java
  back/src/main/java/com/project/mainproject/data/vo/RequestInfoVo.java
  back/src/main/java/com/project/mainproject/data/vo/RequestPageVo.java
  back/src/main/java/com/project/mainproject/medicine/entity/Medicine.java
  back/src/main/java/com/project/mainproject/store/entity/Store.java
  back/src/main/java/com/project/mainproject/store/mapper/StoreMapper.java
  back/src/main/java/com/project/mainproject/store/utils/TransOperatingTime.java
  back/src/main/java/com/project/mainproject/tag/entity/ReviewTag.java
  back/src/main/java/com/project/mainproject/user/entity/PickedStore.java
  back/src/main/java/com/project/mainproject/user/entity/UserBanned.java
  back/src/main/resources/application.yml
Labels: enhancement

#123 Be feat/getStoreDetail서비스 구현 완료
  back/build.gradle
  back/src/main/java/com/project/mainproject/config/QueryDslConfig.java
  back/src/main/java/com/project/mainproject/dto/SliceInfo.java
  back/src/main/java/com/project/mainproject/dto/SliceResponseDto.java
  back/src/main/java/com/project/mainproject/review/entity/Review.java
  back/src/main/java/com/project/mainproject/store/controller/StoreController.java
  back/src/main/java/com/project/mainproject/store/dto/DBdto/DBStoreDetailDto.java
  back/src/main/java/com/project/mainproject/store/dto/DBdto/DBStoreListDto.java
  back/src/main/java/com/project/mainproject/store/dto/GetStoreDetailDto.java
  back/src/main/java/com/project/mainproject/store/dto/GetStoreListRequestDto.java
  back/src/main/java/com/project/mainproject/store/entity/Store.java
  back/src/main/java/com/project/mainproject/store/entity/StoreImage.java
  back/src/main/java/com/project/mainproject/store/repository/StoreQueryRepository.java
  back/src/main/java/com/project/mainproject/store/repository/StoreRepository.java
  back/src/main/java/com/project/mainproject/store/service/StoreGetService.java
  back/src/main/java/com/project/mainproject/store/service/StoreValidService.java
  back/src/main/resources/application.yml
Labels: enhancement

#129 FE_feat/FuncMap 지도 오류 수정 및 클러스터 기능 추가
  front/PharmList.json
  front/package-lock.json
  front/package.json
  front/src/Components/Header/Account.tsx
  front/src/Components/Map/KakaoMap.tsx
  front/src/Components/Map/MapButtons.tsx
  front/src/Components/Map/MapFilter.tsx
  front/src/Components/Map/MapLogic.tsx
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Redux/Store/store.ts
  front/src/Util/UseFetch.tsx
  front/src/Util/z-index.ts
  front/src/hooks/PharmacyOverlay.css
  front/src/hooks/useGeolocation.ts
  front/src/hooks/useMap.ts
  front/tsconfig.json
Labels: enhancement

#133 Fe feat/sign up,login/axios
  front/src/Api/APIs.ts
  front/src/Api/localStorage.ts
  front/src/Components/Modal/PharmDetail.tsx
  front/src/Components/Modal/ReviewUnit.tsx
  front/src/Components/Modal/WriteReviewForm.tsx
  front/src/Components/PharmList/PharmItem.tsx
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Components/SignUpForm/PharmSignForms.tsx
  front/src/Components/SignUpForm/UserSignUpForms.tsx
  front/src/Pages/Admin/Users.tsx
  front/src/Pages/FindPW.tsx
  front/src/Pages/Login.tsx
  front/src/Pages/Pharm/Pharmacy_Information.tsx
  front/src/Pages/User/MyInfo_Information.tsx
  front/src/Pages/User/MyInfo_MyReview.tsx
  front/src/Pages/User/MyInfo_likedPharmacy.tsx
  front/src/Pages/User/MyInfo_likes.tsx
  front/src/Pages/User/MyInfo_reviews.tsx
  front/src/Redux/Store/store.ts
  front/src/Redux/slice/getReviewSlice.ts
  front/src/Redux/slice/userSlice.ts
  front/src/Util/parseJWT.ts
Labels: enhancement

#134 Be feat/store update image service 구현 완료
  back/src/main/java/com/project/mainproject/store/controller/StoreController.java
  back/src/main/java/com/project/mainproject/store/entity/Store.java
  back/src/main/java/com/project/mainproject/store/entity/StoreImage.java
  back/src/main/java/com/project/mainproject/store/service/StoreService.java
  back/src/main/java/com/project/mainproject/user/entity/Pharmacy.java
  back/src/main/java/com/project/mainproject/user/exception/UserExceptionCode.java
  back/src/main/java/com/project/mainproject/user/service/UserService.java
  back/src/main/java/com/project/mainproject/utils/FileUploader.java
Labels: enhancement

#135 Be feat/store service구현 완료
  back/src/main/java/com/project/mainproject/store/controller/StoreController.java
  back/src/main/java/com/project/mainproject/store/dto/DBdto/DBPickedStoredListDto.java
  back/src/main/java/com/project/mainproject/store/dto/DBdto/DBStoreSearchDto.java
  back/src/main/java/com/project/mainproject/store/dto/StoreSearchStoreDto.java
  back/src/main/java/com/project/mainproject/store/entity/Store.java
  back/src/main/java/com/project/mainproject/store/entity/StoreImage.java
  back/src/main/java/com/project/mainproject/store/repository/StoreQueryRepository.java
  back/src/main/java/com/project/mainproject/store/service/StoreGetService.java
  back/src/main/java/com/project/mainproject/store/service/StoreService.java
  back/src/main/java/com/project/mainproject/user/entity/Pharmacy.java
  back/src/main/java/com/project/mainproject/user/entity/PickedStore.java
  back/src/main/java/com/project/mainproject/user/exception/UserExceptionCode.java
  back/src/main/java/com/project/mainproject/user/repository/PickedStoreRepository.java
  back/src/main/java/com/project/mainproject/user/service/UserService.java
  back/src/main/java/com/project/mainproject/utils/FileUploader.java
Labels: enhancement

#145 FE_feat/SearchBar 검색창 수정 및 현 지도에서 재검색 버튼 추가
  front/src/Components/Map/KakaoMap.tsx
  front/src/Components/Map/MapButtons.tsx
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Components/PharmList/SearchBar.tsx
Labels: enhancement

#153 Be hotfix/review
  back/src/main/java/com/project/mainproject/review/controller/ReviewController.java
  back/src/main/java/com/project/mainproject/review/dto/GetReportedReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/GetReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/ListGetReportedReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/ListGetStoreReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/ListGetUserReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/PostUpdateReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/StoreReviewPageDto.java
  back/src/main/java/com/project/mainproject/review/dummy/ReviewStub.java
  back/src/main/java/com/project/mainproject/review/entity/Review.java
  back/src/main/java/com/project/mainproject/review/mapper/ReviewMapper.java
  back/src/main/java/com/project/mainproject/review/repository/ReviewRepository.java
  back/src/main/java/com/project/mainproject/review/service/ReviewService.java
  back/src/main/java/com/project/mainproject/user/dto/UserReviewDto.java
  back/src/main/java/com/project/mainproject/user/dummy/UserStub.java
Labels: enhancement

#157 Be feat/admin_reviews
  back/src/main/java/com/project/mainproject/review/controller/AdminReviewController.java
  back/src/main/java/com/project/mainproject/review/controller/ReviewController.java
  back/src/main/java/com/project/mainproject/review/dto/ReviewIdxDto.java
  back/src/main/java/com/project/mainproject/review/entity/Review.java
  back/src/main/java/com/project/mainproject/review/entity/ReviewReport.java
  back/src/main/java/com/project/mainproject/review/mapper/ReviewReportMapper.java
  back/src/main/java/com/project/mainproject/review/repository/ReviewRepository.java
  back/src/main/java/com/project/mainproject/review/service/ReviewReportService.java
  back/src/main/java/com/project/mainproject/review/service/ReviewService.java
  back/src/main/java/com/project/mainproject/user/dto/BannedReviewsDto.java
Labels: enhancement

#162 Be feat/aop exception 구현완료
  back/src/main/java/com/project/mainproject/exception/ErrorResponse.java
  back/src/main/java/com/project/mainproject/exception/advice/GlobalExceptionAdvice.java
  back/src/main/java/com/project/mainproject/log/LogControllerAop.java
  back/src/main/java/com/project/mainproject/log/PointCut.java
Labels: enhancement

#164 FE_CRUD_enhancement
  front/src/Api/APIs.ts
  front/src/Components/Modal/PharmDetail.tsx
  front/src/Components/Modal/PharmInfo.tsx
  front/src/Components/Modal/ReviewOfReview.tsx
  front/src/Components/Modal/ReviewUnit.tsx
  front/src/Components/Modal/Reviews.tsx
  front/src/Components/Modal/WriteReviewForm.tsx
  front/src/Components/PharmList/PharmItem.tsx
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Components/SignUpForm/ErrorAlert.tsx
  front/src/Components/SignUpForm/SignUpInput.tsx
  front/src/Components/SignUpForm/UserSignUpForms.tsx
  front/src/Components/Ul/PharmRank.tsx
  front/src/Pages/Admin/AdminTabs.tsx
  front/src/Pages/Admin/Cert.tsx
  front/src/Pages/Admin/Certify.tsx
  front/src/Pages/Admin/Reports.tsx
  front/src/Pages/Admin/Users.tsx
  front/src/Pages/FindPW.tsx
  front/src/Pages/Home.tsx
  front/src/Pages/Login.tsx
  front/src/Pages/Pharm/Pharmacist_Information.tsx
  front/src/Pages/Pharm/Pharmacy_Information.tsx
  front/src/Pages/SignUp.tsx
  front/src/Pages/User/MyInfo_Information.tsx
  front/src/Pages/User/MyInfo_MyReview.tsx
  front/src/Pages/User/MyInfo_likedPharmacy.tsx
  front/src/Pages/User/MyInfo_likes.tsx
  front/src/Pages/User/MyInfo_reviews.tsx
  front/src/hooks/useMap.ts
Labels: enhancement

#166 Be_feat/S3 버킷 연동
  back/build.gradle
  back/src/main/java/com/project/mainproject/MainprojectApplication.java
  back/src/main/java/com/project/mainproject/config/S3Config.java
  back/src/main/java/com/project/mainproject/review/service/ReviewService.java
  back/src/main/java/com/project/mainproject/store/service/StoreService.java
  back/src/main/java/com/project/mainproject/utils/FileUploader.java
  back/src/main/resources/application.yml
Labels: enhancement

#167 Be_fit/store 기능변경 구현 완료
  back/src/main/java/com/project/mainproject/exception/advice/GlobalExceptionAdvice.java
  back/src/main/java/com/project/mainproject/security/UserContext.java
  back/src/main/java/com/project/mainproject/store/controller/StoreController.java
  back/src/main/java/com/project/mainproject/store/dto/DBdto/DBStoreDetailDto.java
  back/src/main/java/com/project/mainproject/store/dto/DBdto/DBStoreListDto.java
  back/src/main/java/com/project/mainproject/store/dto/StoreSearchStoreDto.java
  back/src/main/java/com/project/mainproject/store/repository/StoreQueryRepository.java
  back/src/main/java/com/project/mainproject/store/service/StoreGetService.java
  back/src/main/java/com/project/mainproject/user/exception/UserExceptionCode.java
  back/src/main/java/com/project/mainproject/user/service/UserService.java
  back/src/main/java/com/project/mainproject/utils/CheckLoginUser.java
  back/src/main/resources/application-dev.yml
Labels: enhancement

#176 Be feat/user restore 구현 완료
  back/src/main/java/com/project/mainproject/log/LogControllerAop.java
  back/src/main/java/com/project/mainproject/review/dto/PostCreateReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/PostReviewReportDto.java
  back/src/main/java/com/project/mainproject/review/dto/PostUpdateReviewDto.java
  back/src/main/java/com/project/mainproject/review/dto/ReviewIdxDto.java
  back/src/main/java/com/project/mainproject/review/dto/reply/PatchReplyDto.java
  back/src/main/java/com/project/mainproject/review/dto/reply/PostReplyDto.java
  back/src/main/java/com/project/mainproject/security/WebConfig.java
  back/src/main/java/com/project/mainproject/store/dto/GetStoreListRequestDto.java
  back/src/main/java/com/project/mainproject/store/repository/StoreQueryRepository.java
  back/src/main/java/com/project/mainproject/user/controller/AdminController.java
  back/src/main/java/com/project/mainproject/user/dto/AdminUsersDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserFindPasswordDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserPatchDto.java
  back/src/main/java/com/project/mainproject/user/dto/UserSignUpDto.java
  back/src/main/java/com/project/mainproject/user/repository/UserBannedRepository.java
  back/src/main/java/com/project/mainproject/user/service/admin/AdminService.java
Labels: enhancement

#177 BE_Fix: 약사 회원가입
  back/src/main/java/com/project/mainproject/user/service/UserService.java
Labels: fix

#188 BE_fit/storeDetail 오류 수정(운영시간 null 해결)완료
  back/src/main/java/com/project/mainproject/store/mapper/StoreMapper.java
  back/src/main/java/com/project/mainproject/store/utils/TransOperatingTime.java
Labels: bug, fix

#187 FE_CURD_enhancement axios 리팩토링 및 타입 정리
  front/public/Data/Pharm.json
  front/public/Data/PharmList.json
  front/public/Data/Review.json
  front/public/Data/admin_certify.json
  front/public/Data/admin_reports.json
  front/public/Data/admin_users.json
  front/public/Data/pharm_myInfo.json
  front/public/Data/pharm_myPharm.json
  front/public/Data/user_myInfo.json
  front/public/Data/user_myLikes.json
  front/public/Data/user_myReviews.json
  front/src/Api/APIs.ts
  front/src/Api/TYPES.ts
  front/src/Components/Modal/PharmDetail.tsx
  front/src/Components/Modal/PharmInfo.tsx
  front/src/Components/Modal/ReviewOfReview.tsx
  front/src/Components/Modal/ReviewUnit.tsx
  front/src/Components/Modal/Reviews.tsx
  front/src/Components/Modal/WriteReviewForm.tsx
  front/src/Components/PharmList/PharmItem.tsx
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Components/SignUpForm/PharmSignForms.tsx
  front/src/Components/SignUpForm/UserSignUpForms.tsx
  front/src/Components/Ul/PharmRank.tsx
  front/src/Pages/Admin/Cert.tsx
  front/src/Pages/Admin/Certify.tsx
  front/src/Pages/Admin/ImageUp.tsx
  front/src/Pages/Admin/Reports.tsx
  front/src/Pages/Admin/Users.tsx
  front/src/Pages/FindPW.tsx
  front/src/Pages/Home.tsx
  front/src/Pages/Login.tsx
  front/src/Pages/Pharm/DropDown.tsx
  front/src/Pages/Pharm/Pharmacist_Information.tsx
  front/src/Pages/Pharm/Pharmacy_Information.tsx
  front/src/Pages/SignOut.tsx
  front/src/Pages/User/MyInfo_Information.tsx
  front/src/Pages/User/MyInfo_MyReview.tsx
  front/src/Pages/User/MyInfo_likedPharmacy.tsx
  front/src/Pages/User/MyInfo_likes.tsx
  front/src/Pages/User/MyInfo_reviews.tsx
  front/tsconfig.json
Labels: enhancement

#190 BE_Fix: 비밀번호 유효성 변경
  back/src/main/java/com/project/mainproject/user/service/UserService.java
Labels: fix

#191 FE_merge/merge
  front/package-lock.json
  front/package.json
  front/src/App.tsx
  front/src/Components/Header/Account.tsx
  front/src/Components/Header/Header.tsx
  front/src/Components/Header/Layout.tsx
  front/src/Components/Modal/PharmDetail.tsx
  front/src/Components/Modal/PharmInfo.tsx
  front/src/Components/Modal/ReviewOfReview.tsx
  front/src/Components/Modal/ReviewUnit.tsx
  front/src/Components/Modal/Reviews.tsx
  front/src/Components/Modal/WriteReviewForm.tsx
  front/src/Components/PharmList/PharmItem.tsx
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Pages/FindPW.tsx
  front/src/Pages/Login.tsx
  front/src/Pages/Pharm/Pharmacist_Information.tsx
  front/src/Pages/Pharm/Pharmacy_Information.tsx
  front/src/Pages/SignOut.tsx
  front/src/Pages/User/MyInfo_Information.tsx
  front/src/Pages/User/MyInfo_MyReview.tsx
  front/src/Pages/User/MyInfo_likedPharmacy.tsx
  front/src/Pages/User/MyInfo_likes.tsx
  front/src/Pages/User/MyInfo_reviews.tsx
  front/src/Redux/slice/userSlice.ts
  front/src/Redux/store/store.ts
  front/src/main.tsx
Labels: enhancement

#192 FE_fix/mapMarker 지도 기능 보완
  front/package-lock.json
  front/package.json
  front/public/Images/ImgPreparing.png
  front/public/Images/NoPharmImg.png
  front/public/Images/map.png
  front/src/Api/APIs.ts
  front/src/Components/Map/KakaoMap.tsx
  front/src/Components/Map/MapButtons.tsx
  front/src/Components/Map/MapFilter.tsx
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Components/PharmList/SearchBar.tsx
  front/src/Components/PharmList/SortButtons.tsx
  front/src/Components/Ul/Loading.tsx
  front/src/Pages/Home.tsx
  front/src/Util/type.ts
  front/src/Util/z-index.ts
  front/src/hooks/useMap.ts
  front/src/hooks/useMapMarker.ts
Labels: enhancement, fix

#202 FE 마무리
  front/public/Images/Pharm.png
  front/public/Images/User.png
  front/public/Images/쌍화탕.jpg
  front/src/Api/APIs.ts
  front/src/Components/Header/Account.tsx
  front/src/Components/Modal/PharmDetail.tsx
  front/src/Components/Modal/PharmInfo.tsx
  front/src/Components/Modal/ReplyOfReview.tsx
  front/src/Components/Modal/ReviewUnit.tsx
  front/src/Components/Modal/WriteReviewForm.tsx
  front/src/Components/PharmList/PharmItem.tsx
  front/src/Components/SignUpForm/PharmSignForms.tsx
  front/src/Pages/Admin/Cert.tsx
  front/src/Pages/Admin/Certify.tsx
  front/src/Pages/Admin/Reports.tsx
  front/src/Pages/Admin/Users.tsx
  front/src/Pages/FindPW.tsx
  front/src/Pages/Login.tsx
  front/src/Pages/Pharm/Pharmacist_Information.tsx
  front/src/Pages/Pharm/Pharmacy_Information.tsx
  front/src/Pages/User/MyInfo_Information.tsx
  front/src/Pages/User/MyInfo_MyReview.tsx
  front/src/Pages/User/MyInfo_likedPharmacy.tsx
  front/src/Pages/User/MyInfo_likes.tsx
  front/src/Pages/User/MyInfo_reviews.tsx
  front/src/hooks/useMapMarker.ts
Labels: enhancement

#203 Be doc/store 독스 1차 완성
  back/build.gradle
  back/src/main/java/com/project/mainproject/security/UserContext.java
  back/src/main/java/com/project/mainproject/store/controller/StoreController.java
  back/src/main/java/com/project/mainproject/store/dto/DBdto/DBPickedStoredListDto.java
  back/src/main/java/com/project/mainproject/store/dto/DBdto/DBStoreDetailDto.java
  back/src/main/java/com/project/mainproject/store/dto/DBdto/DBStoreListDto.java
  back/src/main/java/com/project/mainproject/store/dto/DBdto/DBStoreSearchDto.java
  back/src/main/java/com/project/mainproject/store/dto/FilterTagDto.java
  back/src/main/java/com/project/mainproject/store/dto/GetPickedStoreDto.java
  back/src/main/java/com/project/mainproject/store/dto/GetStoreHomeDto.java
  back/src/main/java/com/project/mainproject/store/dto/GetStoreHomeListDto.java
  back/src/main/java/com/project/mainproject/store/dto/GetStoreListRequestDto.java
  back/src/main/java/com/project/mainproject/store/dto/StoreIdxResponse.java
  back/src/main/java/com/project/mainproject/store/dummy/StoreStub.java
  back/src/main/java/com/project/mainproject/store/repository/StoreQueryRepository.java
  back/src/main/java/com/project/mainproject/store/service/StoreGetService.java
  back/src/main/java/com/project/mainproject/stub/CommonStub.java
  back/src/main/java/com/project/mainproject/user/controller/UserController.java
  back/src/test/java/com/project/mainproject/helper/ControllerTestHelper.java
  back/src/test/java/com/project/mainproject/helper/store/StoreControllerTestHelper.java
  back/src/test/java/com/project/mainproject/review/controller/ReviewAdminControllerTest.java
  back/src/test/java/com/project/mainproject/store/controller/StoreControllerTest.java
  back/src/test/java/com/project/mainproject/stub/CommonStub.java
  back/src/test/java/com/project/mainproject/stub/StoreStub.java
Labels: documentation, fix

#204 BE_doc/storeDocs 실제 적용을 위한 코드 수정
  back/src/main/java/com/project/mainproject/store/controller/StoreController.java
  back/src/test/java/com/project/mainproject/helper/store/StoreControllerTestHelper.java
  back/src/test/java/com/project/mainproject/store/controller/StoreControllerTest.java
Labels: bug, documentation, be deploy

#206 Be hotfix/store search수정 완료
  back/src/main/java/com/project/mainproject/review/controller/ReviewController.java
  back/src/main/java/com/project/mainproject/store/repository/StoreQueryRepository.java
  back/src/main/java/com/project/mainproject/store/service/StoreGetService.java
Labels: bug, be deploy

#207 Be deploy labeled test
  .github/workflows/deploy_test.yml
  back/src/main/resources/application-dev.yml
  back/src/main/resources/application.yml
Labels: be deploy

#209 BE_Deploy: actions trigger yml 경로 변경
  .github/workflows/deploy_test.yml
Labels: be deploy

#210 BE_Deploy: actions trigger yml 경로 변경
  .github/workflows/deploy_test.yml
Labels: be deploy

#211 BE_Deploy: actions trigger yml 경로 변경
  .github/workflows/deploy_test.yml
Labels: be deploy

#212 BE_Deploy: 테스트 코드 임시 삭제
  back/src/test/java/com/project/mainproject/review/controller/ReviewAdminControllerTest.java
  back/src/test/java/com/project/mainproject/store/controller/StoreControllerTest.java
Labels: be deploy

#213 BE_Deploy: actions trigger yml 경로 변경
  .github/workflows/deploy_test.yml
Labels: be deploy

#214 Be feat/mail sender구현 임시 완료
  back/build.gradle
  back/src/main/java/com/project/mainproject/mail/EmailConfig.java
  back/src/main/java/com/project/mainproject/mail/EmailSendable.java
  back/src/main/java/com/project/mainproject/mail/EmailSender.java
  back/src/main/java/com/project/mainproject/mail/SimpleEmailSendable.java
  back/src/main/java/com/project/mainproject/mail/TemplateEmailSendable.java
  back/src/main/java/com/project/mainproject/mail/event/UserFindPasswordApplicationEvent.java
  back/src/main/java/com/project/mainproject/mail/event/UserFindPasswordEventListener.java
  back/src/main/java/com/project/mainproject/user/service/UserService.java
  back/src/main/resources/templates/email-registration-member.html
Labels: be deploy

#215 BE_Deploy: dev_deploy.yml 삭제
  .github/workflows/dev_deploy
Labels: be deploy

#216 BE_Fix: 회원 작성 리뷰 조회 시 storeIdx 추가
  back/src/main/java/com/project/mainproject/review/dto/ListGetUserReviewDto.java
  back/src/main/java/com/project/mainproject/review/mapper/ReviewMapper.java
Labels: be deploy

#217 BE_Fix: yml 구조 변경
  back/src/main/resources/application-dev.yml
  back/src/main/resources/application-test.yml
  back/src/main/resources/application.yml
Labels: enhancement

#219 BE_Fix: 패스워드 불일치 해결
  back/src/main/java/com/project/mainproject/MainprojectApplication.java
Labels: fix

#222 Be deploy labeled test
  .github/workflows/deploy_test.yml
  .idea/.gitignore
  back/.gitignore
  back/build.gradle
  back/src/main/java/com/project/mainproject/mail/EmailConfig.java
  back/src/main/java/com/project/mainproject/mail/EmailSendable.java
  back/src/main/java/com/project/mainproject/mail/EmailSender.java
  back/src/main/java/com/project/mainproject/mail/SimpleEmailSendable.java
  back/src/main/java/com/project/mainproject/mail/TemplateEmailSendable.java
  back/src/main/java/com/project/mainproject/mail/event/UserFindPasswordApplicationEvent.java
  back/src/main/java/com/project/mainproject/mail/event/UserFindPasswordEventListener.java
  back/src/main/java/com/project/mainproject/review/controller/ReviewController.java
  back/src/main/java/com/project/mainproject/review/dto/ListGetUserReviewDto.java
  back/src/main/java/com/project/mainproject/review/mapper/ReviewMapper.java
  back/src/main/java/com/project/mainproject/store/repository/StoreQueryRepository.java
  back/src/main/java/com/project/mainproject/store/service/StoreGetService.java
  back/src/main/java/com/project/mainproject/user/service/UserService.java
  back/src/main/resources/application-dev.yml
  back/src/main/resources/application-test.yml
  back/src/main/resources/templates/email-registration-member.html
  front/index.html
  front/package.json
  front/public/Images/favicon.ico
  front/src/Api/APIs.ts
  front/vite.config.ts
Labels: be deploy

#223 BE_Deploy: actions trigger yml 수정
  .github/workflows/deploy_test.yml
Labels: be deploy

#225 BE_Deploy: actions trigger yml 수정
  .github/workflows/deploy_test.yml
Labels: be deploy

#226 BE_Delpoy: ssh-actions version 변경
  .github/workflows/deploy_test.yml
Labels: be deploy

#227 Be doc/review docs수정 완료
  back/src/main/java/com/project/mainproject/review/dto/PostReviewReportDto.java
  back/src/main/java/com/project/mainproject/review/dto/ReviewIdxDto.java
  back/src/main/java/com/project/mainproject/review/dto/reply/PatchReplyDto.java
  back/src/main/java/com/project/mainproject/review/dto/reply/PostReplyDto.java
  back/src/main/java/com/project/mainproject/review/entity/ReviewReport.java
  back/src/test/java/com/project/mainproject/helper/ControllerTestHelper.java
  back/src/test/java/com/project/mainproject/helper/review/ReviewControllerTestHelper.java
  back/src/test/java/com/project/mainproject/helper/review/ReviewReplyControllerTestHelper.java
  back/src/test/java/com/project/mainproject/review/controller/AdminReviewControllerTest.java
  back/src/test/java/com/project/mainproject/review/controller/ReviewAdminControllerTest.java
  back/src/test/java/com/project/mainproject/review/controller/ReviewControllerTest.java
  back/src/test/java/com/project/mainproject/review/controller/ReviewReplyControllerTest.java
  back/src/test/java/com/project/mainproject/stub/ReviewStub.java
Labels: documentation, be deploy

#228 BE_Delpoy: ssh-actions rsa
  .github/workflows/deploy_test.yml
Labels: be deploy

#229 BE_Delpoy: ssh-actions rsa
  .github/workflows/deploy_test.yml
Labels: be deploy

#230 BE_Delpoy: Dockerfile
  back/Dockerfile
  back/src/main/resources/keystore.p12
Labels: be deploy

#231 BE_Delpoy: Dockerfile
  back/Dockerfile
Labels: be deploy

#232 BE_Delpoy: actions 마지막
  .github/workflows/deploy_test.yml
Labels: be deploy

#233 BE_Delpoy: Dockerfile jar 경로 변경
  back/Dockerfile
Labels: be deploy

#234 BE_Delpoy: Dockerfile jar 경로 변경
  back/Dockerfile
Labels: be deploy

#235 BE_Delpoy: Dockerfile 수정
  .github/workflows/deploy_test.yml
  back/Dockerfile
Labels: be deploy

#236 BE_Fix: 회원 정보 수정 기능 버그 해결
  back/src/main/java/com/project/mainproject/user/service/UserService.java
Labels: fix

#240 BE_Deploy: Dockerfile 환경변수 설정
  .github/workflows/deploy_test.yml
Labels: be deploy

#245 BE_Feat: 리뷰 신고 상태 기본값 설정
  back/src/main/java/com/project/mainproject/review/entity/ReviewReport.java
Labels: fix

#247 BE_Feat: 리뷰 신고 상태 세팅
  back/src/main/java/com/project/mainproject/review/entity/ReviewReport.java
  back/src/main/java/com/project/mainproject/review/service/ReviewReportService.java
Labels: fix

#248 BE_Fix: 약국 검색 수정
  back/src/main/java/com/project/mainproject/store/controller/StoreController.java
  back/src/main/java/com/project/mainproject/store/dto/DBdto/DBStoreSearchDto.java
  back/src/main/java/com/project/mainproject/store/repository/StoreQueryRepository.java
  back/src/main/java/com/project/mainproject/store/service/StoreGetService.java
  back/src/test/java/com/project/mainproject/stub/StoreStub.java
Labels: fix

#253 BE_Deploy: secret 설정
  .github/workflows/deploy_test.yml
Labels: be deploy

#255 Be deploy labeled test
  .github/workflows/deploy_test.yml
Labels: be deploy

#257 BE_Deploy: env 파일 설정
  .github/workflows/deploy_test.yml
  back/.env
Labels: be deploy

#258 Be deploy labeled test
  .github/workflows/deploy_test.yml
Labels: be deploy

#259 BE_Deploy: Parameter Store
  .github/workflows/deploy_test.yml
  back/.env
  back/build.gradle
  back/src/main/resources/application-pro.yml
  back/src/main/resources/bootstrap.yml
Labels: be deploy

#273 BE_Deploy: CI 설정
  .github/workflows/dev_deploy
  back/.gitignore
  back/Dockerfile
  back/src/main/resources/application-pro.yml
Labels: be deploy

#274 BE_Deploy: Github actions workflow 동작 시 빌드 오류로 인한 테스트코드 임시 주석처리
  back/src/test/java/com/project/mainproject/MainprojectApplicationTests.java
  back/src/test/java/com/project/mainproject/review/controller/AdminReviewControllerTest.java
  back/src/test/java/com/project/mainproject/review/controller/ReviewControllerTest.java
  back/src/test/java/com/project/mainproject/review/controller/ReviewReplyControllerTest.java
  back/src/test/java/com/project/mainproject/store/controller/StoreControllerTest.java
  back/src/test/java/com/project/mainproject/user/controller/AdminControllerTest.java
  back/src/test/java/com/project/mainproject/user/controller/UserControllerTest.java
Labels: be deploy

#275 BE_Deploy: Dockerfile 수정
  back/Dockerfile
Labels: be deploy

#277 BE_Deploy: Docker Volume 설정
  back/Dockerfile
Labels: be deploy

#242 FE_feat/MoveToMyPlace
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Components/PharmList/SearchBar.tsx
  front/src/Pages/Home.tsx
  front/src/Util/type.ts
  front/src/hooks/useMapMarker.ts
Labels: enhancement

#281 Be hotfix/user page
  back/src/main/java/com/project/mainproject/user/controller/UserController.java
Labels: enhancement, fix

#282 BE_Feat: 리뷰 조회 시 약국 검증 추가
  back/src/main/java/com/project/mainproject/review/service/ReviewService.java
  back/src/main/java/com/project/mainproject/store/service/StoreValidService.java
Labels: be deploy

#283 Be feat/monitoring구현
  back/build.gradle
  back/src/main/java/com/project/mainproject/security/JwtHelper.java
  back/src/main/resources/application-dev.yml
  back/src/main/resources/application-test.yml
Labels: be deploy

#285 Be feat/scheduler
  back/src/main/java/com/project/mainproject/MainprojectApplication.java
  back/src/main/java/com/project/mainproject/review/repository/ReviewReportRepository.java
  back/src/main/java/com/project/mainproject/review/repository/ReviewRepository.java
  back/src/main/java/com/project/mainproject/scheduler/review/ReviewScheduler.java
Labels: enhancement, be deploy

#286 BE_test: 배포 테스트
  back/src/test/java/com/project/mainproject/store/controller/StoreControllerTest.java
Labels: be deploy

#287 BE_Feat: 스케줄링_리뷰 매시 0분 작동
  back/src/main/java/com/project/mainproject/scheduler/review/ReviewScheduler.java
Labels: be deploy

#288 Be feat/scheduler
  back/src/main/java/com/project/mainproject/scheduler/review/ReviewScheduler.java
Labels: be deploy

#289 BE_fix : Userlogin시 Usertype추가
  back/src/main/java/com/project/mainproject/security/AuthenticationFilter.java
  back/src/main/java/com/project/mainproject/user/dto/UserLoginInfoResponse.java
Labels: be deploy

#290 BE_Feat: 스케줄링_휴면회원
  back/src/main/java/com/project/mainproject/mail/event/UserSleepNotificationApplicationEvent.java
  back/src/main/java/com/project/mainproject/mail/event/UserSleepNotificationEventListener.java
  back/src/main/java/com/project/mainproject/scheduler/user/UserScheduler.java
  back/src/main/java/com/project/mainproject/user/repository/UserRepository.java
  back/src/main/resources/logback.xml
  back/src/main/resources/templates/email-sleep-notification.html
Labels: be deploy

#291 BE_Feat: 스케줄링_정지회원 자동 복구, 휴면 회원 전환 수정
  back/src/main/java/com/project/mainproject/scheduler/user/UserScheduler.java
  back/src/main/java/com/project/mainproject/user/repository/UserBannedRepository.java
  back/src/main/java/com/project/mainproject/user/repository/UserRepository.java
  back/src/main/java/com/project/mainproject/user/service/admin/AdminService.java
Labels: be deploy

#292 Fe fix/errors
  front/src/Api/AxiosInstance.ts
  front/src/Api/TYPES.ts
  front/src/Components/Header/Account.tsx
  front/src/Components/Modal/ReplyOfReview.tsx
  front/src/Components/Modal/ReviewUnit.tsx
  front/src/Components/Modal/Reviews.tsx
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Pages/Admin/Certify.tsx
  front/src/Pages/Admin/Reports.tsx
  front/src/Pages/Admin/Users.tsx
  front/src/Pages/Login.tsx
  front/src/Pages/Pharm/Pharmacist_Information.tsx
  front/src/Pages/Pharm/Pharmacy_Information.tsx
  front/src/Pages/User/MyInfo_Information.tsx
  front/src/Redux/slice/userSlice.ts
Labels: fix

#294 Be feat/review
  back/src/main/java/com/project/mainproject/review/exception/ReviewExceptionCode.java
  back/src/main/java/com/project/mainproject/review/repository/ReviewRepository.java
  back/src/main/java/com/project/mainproject/review/service/ReviewService.java
  back/src/main/java/com/project/mainproject/user/entity/User.java
Labels: be deploy

#295 Be feat/review
  back/src/main/java/com/project/mainproject/review/controller/ReviewController.java
  back/src/main/java/com/project/mainproject/review/exception/ReviewExceptionCode.java
  back/src/main/java/com/project/mainproject/review/service/ReviewReportService.java
  back/src/main/java/com/project/mainproject/review/service/ReviewService.java
Labels: fix, be deploy

#296 Be fit/store배포 중 Store 문제 해결
  back/src/main/java/com/project/mainproject/store/dto/DBdto/DBStoreSearchDto.java
  back/src/main/java/com/project/mainproject/store/entity/Store.java
  back/src/main/java/com/project/mainproject/store/repository/StoreQueryRepository.java
  back/src/main/java/com/project/mainproject/store/service/StoreGetService.java
Labels: be deploy

#297 BE_fit/ 작업 완료
  back/src/main/java/com/project/mainproject/dto/SingleResponseDto.java
  back/src/main/java/com/project/mainproject/store/dto/DBdto/DBStoreSearchDto.java
Labels: be deploy

#298 BE_fit/데이터 파악을 위한 로깅
  back/src/main/java/com/project/mainproject/store/dto/DBdto/DBStoreSearchDto.java
  back/src/main/java/com/project/mainproject/store/service/StoreGetService.java
Labels: be deploy

#299 Be_feat/review 별점 검증 0점~5점
  back/src/main/java/com/project/mainproject/review/controller/ReviewController.java
  back/src/main/java/com/project/mainproject/review/exception/ReviewExceptionCode.java
  back/src/main/java/com/project/mainproject/review/service/ReviewService.java
Labels: be deploy

#300 BE_Refactor: DB 초기화 전 JoinColumn 정리
  back/src/main/java/com/project/mainproject/dto/SingleResponseDto.java
  back/src/main/java/com/project/mainproject/review/entity/ReviewReply.java
  back/src/main/java/com/project/mainproject/review/entity/ReviewReport.java
  back/src/main/java/com/project/mainproject/user/entity/PickedStore.java
  back/src/main/java/com/project/mainproject/user/entity/UserBanned.java
Labels: be deploy

#303 BE_feat/회원 여부 검증 로직 추가완료
  back/src/main/java/com/project/mainproject/user/service/UserService.java
Labels: be deploy

#305 Be feat/review
  back/src/main/java/com/project/mainproject/review/entity/Review.java
  back/src/main/java/com/project/mainproject/review/service/ReviewReportService.java
  back/src/main/java/com/project/mainproject/user/service/UserService.java
Labels: be deploy

#304 Fe fix/try(아직 머지하지 마세요! 아침에 같이 하기로함)
  front/src/Api/AxiosInstance.ts
  front/src/Components/Header/Header.tsx
  front/src/Components/Map/MapButtons.tsx
  front/src/Components/Modal/ReviewUnit.tsx
  front/src/Components/Modal/WriteReviewForm.tsx
  front/src/Components/PharmList/PharmItem.tsx
  front/src/Components/PharmList/PharmLists.tsx
  front/src/Components/SignUpForm/PharmSignForms.tsx
  front/src/Pages/Login.tsx
Labels: fix

#308 Be_feat/review
  back/src/main/java/com/project/mainproject/review/controller/AdminReviewController.java
  back/src/main/java/com/project/mainproject/review/controller/ReviewController.java
  back/src/main/java/com/project/mainproject/review/controller/ReviewReplyController.java
  back/src/main/java/com/project/mainproject/review/dto/ListGetStoreReviewDto.java
  back/src/main/java/com/project/mainproject/review/exception/ReviewExceptionCode.java
  back/src/main/java/com/project/mainproject/review/mapper/ReviewMapper.java
  back/src/main/java/com/project/mainproject/review/service/ReviewReplyService.java
  back/src/main/java/com/project/mainproject/review/service/ReviewService.java
Labels: be deploy

#310 Be feat/review 약국 리뷰 페이징 제거
  .github/workflows/deploy.yml
  back/src/main/java/com/project/mainproject/review/controller/ReviewController.java
  back/src/main/java/com/project/mainproject/review/repository/ReviewRepository.java
  back/src/main/java/com/project/mainproject/review/service/ReviewService.java
  back/src/test/java/com/project/mainproject/helper/ControllerTestHelper.java
  back/src/test/java/com/project/mainproject/review/controller/ReviewControllerTest.java
  back/src/test/java/com/project/mainproject/review/controller/ReviewReplyControllerTest.java
Labels: be deploy

#311 BE_Feat: 테스트 코드 빌드 해결 시도
  back/src/test/java/com/project/mainproject/MainprojectApplicationTests.java
Labels: be deploy

#312 Be feat/review
  back/src/test/resources/application.yml
Labels: be deploy

#313 BE_Feat: 테스트 코드 빌드 해결 시도
  back/src/test/java/com/project/mainproject/MainprojectApplicationTests.java
  back/src/test/resources/application.yml
Labels: be deploy

#315 BE_Feat: 찜콩 약국 비로그인 요청 시 예외 추가
  back/src/main/java/com/project/mainproject/store/service/StoreGetService.java
Labels: be deploy

#316 BE_fit/운영시간여부 반대로 작성했던 부분 변경 수정완료
  back/src/main/java/com/project/mainproject/VO/OperatingTime.java
Labels: be deploy
